databases:
  - name: cheap-ships
    databaseName: cheap-ships
    user: cheap-ships

services:
  - type: web
    name: cheap-ships
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cheap-ships
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
