databases:
  - name: cheap_ships
    databaseName: cheap_ships
    user: cheap_ships

services:
  - type: web
    name: cheap_ships
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cheap_ships
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
